### PR TITLE
Artifact Power Items support

### PR DESCRIPTION
**Pull request by Tarkumi**

### CODE REVIEW

**Comment by ckaotik** [comment]
Please note that this does not yet work for non-English locales. [WowHead](http://de.wowhead.com/search?q=macht+verleihen) has a list of the spells (deDE locale in this case). Best would probably be to pick one of these spell ids and compare against the name returned by `GetSpellInfo()`.

**Comment by tekkub** [comment]
Awesome addition.  I've merged it with what should be a more robust localization.

**Comment by ckaotik** [comment]
Awesome! However I think you got the wrong translation. There seems to be more than just the artifact empowering effects named "Empowering", that's why I linked the German list :) "
Macht verleihen" would be the correct translation in this case. I think this probably also affects other locales.

**Comment by tekkub** [comment]
@ckaotik I get the spell name in 7913a4bc5773766256f039ca4def25e6fca897fa, so it *should* work on any locale.

**Comment by ckaotik** [comment]
@tekkub Oh, nevermind, I must have been looking at the PR code instead of the actual commit. My bad, sorry!

**Pull request closed without merging**
